repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        files: \.(c|h|cpp|hpp)$
        entry: clang-format -i
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: 'src/tests/inputs/ar/.+\.a'
      - id: trailing-whitespace
        exclude: 'src/tests/inputs/ar/.+\.a'
      - id: check-merge-conflict
  - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: v0.6.2
    hooks:
      - id: cmake-format
        exclude: build
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
